// Code generated by go-bindata.
// sources:
// webserver/templates/bottom.html
// webserver/templates/home.html
// webserver/templates/top.html
// DO NOT EDIT!

package webserver

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"strings"
	"os"
	"time"
	"io/ioutil"
	"path/filepath"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name string
	size int64
	mode os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _templatesBottomHtml = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xaa\xae\x56\x48\x49\x4d\xcb\xcc\x4b\x55\x50\x4a\xca\x2f\x29\xc9\xcf\x55\x52\xa8\xad\xe5\xb2\xd1\x4f\xca\x4f\xa9\xb4\x03\xd2\x19\x25\xb9\x39\x76\x5c\x40\x55\xa9\x79\x29\x40\x19\x40\x00\x00\x00\xff\xff\xfb\x3f\xb1\xdd\x2f\x00\x00\x00")

func templatesBottomHtmlBytes() ([]byte, error) {
	return bindataRead(
		_templatesBottomHtml,
		"templates/bottom.html",
	)
}

func templatesBottomHtml() (*asset, error) {
	bytes, err := templatesBottomHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/bottom.html", size: 47, mode: os.FileMode(436), modTime: time.Unix(1441558854, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _templatesHomeHtml = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x4c\x8f\x4d\x6a\x85\x30\x10\x80\xd7\xef\x9d\x62\xc8\x01\x74\xd1\x5d\xb1\x42\x8b\x52\x04\x91\x52\xdb\x03\x44\x1c\x35\x90\x3f\x9a\x71\x15\xbc\x7b\x27\xb1\xf4\xb9\x9c\x2f\xdf\x7c\x64\x62\x84\x19\x17\x65\x11\xc4\xe6\x0c\x0a\x38\x8e\xfb\x2d\x46\x42\xe3\xb5\x24\xa6\xe4\xbc\x80\x82\xe9\xfd\x56\x6d\x4f\x75\xd8\x3d\xa8\x00\xbc\xa6\x16\x28\xd0\xca\x49\xe3\xcc\x4b\xf0\xf9\x3d\x0c\xdd\xf0\x9e\x5e\x50\x07\x4c\xa8\xe9\xc6\xd7\xb7\xbe\x6d\x32\xb3\xc9\xaa\x4a\x4e\xa4\x92\x84\xed\x07\x97\x17\x51\x92\x5b\x57\x8d\xed\xd9\x11\xf5\x39\xc2\x5f\xb7\x2a\x65\xb6\x7d\xdd\xcb\x40\x10\x48\xd2\x1e\x9e\x53\xae\xd0\x0c\xc6\x3c\xe7\xac\xbf\x7a\x5e\xd9\x15\x48\x19\x4c\x6a\x36\x3f\x98\x7c\x31\x78\xb8\xd7\x13\x27\x47\xe4\xcc\x79\xe5\xff\x57\x7f\x03\x00\x00\xff\xff\x6c\x3d\xb4\xa9\x19\x01\x00\x00")

func templatesHomeHtmlBytes() ([]byte, error) {
	return bindataRead(
		_templatesHomeHtml,
		"templates/home.html",
	)
}

func templatesHomeHtml() (*asset, error) {
	bytes, err := templatesHomeHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/home.html", size: 281, mode: os.FileMode(436), modTime: time.Unix(1441561884, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _templatesTopHtml = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xaa\xae\x56\x48\x49\x4d\xcb\xcc\x4b\x55\x50\x2a\xc9\x2f\x50\x52\xa8\xad\xe5\xb2\x51\x74\xf1\x77\x0e\x89\x0c\x70\x55\xc8\x28\xc9\xcd\xb1\xe3\xb2\x81\x51\xa9\x89\x29\x76\x36\xfa\x60\x8a\xcb\x26\x29\x3f\xa5\x12\x24\x68\x68\x17\x1c\x1a\x00\x14\x35\xb4\xe3\x02\x9a\x95\x9a\x97\x02\x34\x02\x10\x00\x00\xff\xff\xa2\x9a\x7b\xc9\x55\x00\x00\x00")

func templatesTopHtmlBytes() ([]byte, error) {
	return bindataRead(
		_templatesTopHtml,
		"templates/top.html",
	)
}

func templatesTopHtml() (*asset, error) {
	bytes, err := templatesTopHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/top.html", size: 85, mode: os.FileMode(436), modTime: time.Unix(1441560114, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if (err != nil) {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"templates/bottom.html": templatesBottomHtml,
	"templates/home.html": templatesHomeHtml,
	"templates/top.html": templatesTopHtml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"templates": &bintree{nil, map[string]*bintree{
		"bottom.html": &bintree{templatesBottomHtml, map[string]*bintree{
		}},
		"home.html": &bintree{templatesHomeHtml, map[string]*bintree{
		}},
		"top.html": &bintree{templatesTopHtml, map[string]*bintree{
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
        data, err := Asset(name)
        if err != nil {
                return err
        }
        info, err := AssetInfo(name)
        if err != nil {
                return err
        }
        err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
        if err != nil {
                return err
        }
        err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
        if err != nil {
                return err
        }
        err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
        if err != nil {
                return err
        }
        return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
        children, err := AssetDir(name)
        // File
        if err != nil {
                return RestoreAsset(dir, name)
        }
        // Dir
        for _, child := range children {
                err = RestoreAssets(dir, filepath.Join(name, child))
                if err != nil {
                        return err
                }
        }
        return nil
}

func _filePath(dir, name string) string {
        cannonicalName := strings.Replace(name, "\\", "/", -1)
        return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

